#!/usr/bin/bash

### Takes package-license.txt as positional argument

while read line; do
        package="$(echo $line | cut -d':' -f1 )"
        #echo "Testing $package"
        license-validate "$(echo $line | cut -d':' -f2 )" >/dev/null || echo "$package"
done < "$1"

