#!/usr/bin/bash

### Takes package-license.txt as positional argument

while read line; do
        echo Testing $(echo $line | cut -d':' -f1 )
        license-validate "$(echo $line | cut -d':' -f2 )"
done < "$1"

