#!/usr/bin/bash

LICENSE='GPL+ or Artistic'
### Takes list of packages as positional argument

count=0

while read line; do
        echo $line
        ./convert-spec-universal.py "rpm-specs/$line.spec" "$LICENSE"
        ((count++))
        if [ "$count" -ge 500 ]; then
                break
        fi
done < "$1"

