#!/usr/bin/bash

LICENSE='GPL+ or Artistic'
### Takes list of packages as positional argument


while read line; do
        echo $line
        ./convert-spec-universal.py "rpm-specs/$line.spec" "$LICENSE"
done < "$1"

