#!/usr/bin/bash

LICENSE='SPL'
### Takes list of packages as positional argument


for line in $(cat $1); do
        cd /tmp
        fedpkg clone "$line"
        cd "$line"
        /home/msuchy/projects/license-validate/convert-spec.py "$line.spec" "$LICENSE"
        git commit -a -m "convert $LICENSE license to SPDX

This is part of https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_4"
        git show
        echo "Check commit. Hit Ctrl+D when you are ready. git-push will be done automatically"
        bash
        git push
done

